import { useQuery } from "@tanstack/react-query";
import type { StatsData } from "@/lib/stats";

// stats.json is a static asset regenerated by the build-stats cron (~every 2h),
// so there's nothing to poll — fetch once and treat it as fresh for a while.
async function fetchStats(): Promise<StatsData> {
  const res = await fetch("/stats.json", { cache: "no-store" });
  if (!res.ok) throw new Error(`/stats.json returned ${res.status}`);
  return res.json();
}

export function useStats() {
  return useQuery({
    queryKey: ["stats"],
    queryFn: fetchStats,
    staleTime: 10 * 60 * 1000,
  });
}
